version: '3.7'

services:
  webrtcdemo:
    image: ${DOCKER_REGISTRY-}webrtcdemo
    ports:
        - 8000:80
        - 4443:443
    build:
      context: .
      dockerfile: WebRTCDemo/Dockerfile
